### ISSUE TITLE
where is package #import "@preview/book:0.2.5": ?

### ISSUE THREAD

**Issue by Rainboylvx** [Myriad-Dreamin/typst-book#63]
I found code `#import "@preview/book:0.2.5": *` in `/templates/ebook.typ`. But  I am not found package book in `https://github.com/typst/packages/tree/main/packages/preview`. So where is the source code of `@preview/book:0.2.5`?

**Comment by Myriad-Dreamin** [comment]
It is here. https://github.com/Myriad-Dreamin/typst-book/tree/main/contrib/typst/book
The typst template code was write at typst 0.3.0. now typst supports template packages since 0.11.0, we can publish it as a template.

**Comment by Rainboylvx** [comment]
> It is here. https://github.com/Myriad-Dreamin/typst-book/tree/main/contrib/typst/book The typst template code was write at typst 0.3.0. now typst supports template packages since 0.11.0, we can publish it as a template.

thank you! please publish it as typst packages
